using RPGCharacterService.Persistence;
using RPGCharacterService.Services;

var builder = WebApplication.CreateBuilder(args);

// Add services to DI container
builder.Services.AddControllers();
builder.Services.AddSingleton<ICharacterRepository, InMemoryCharacterRepository>();
builder.Services.AddScoped<ICharacterService, CharacterService>();
builder.Services.AddScoped<ICurrencyService, CurrencyService>();
builder.Services.AddScoped<IStatsService, StatsService>();
builder.Services.AddSingleton<IDiceService, DiceService>();

// Add Swagger services
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    // Use Swagger Comments for better self-documentation
    c.EnableAnnotations();
});

var app = builder.Build();

// Enable static files (important to serve openapi.json)
app.UseStaticFiles();

// Enable Swagger Middleware
app.UseSwagger();
app.UseSwaggerUI(c =>
{
    // Use the swagger.json file generated by the Swagger service
    // Serve Swagger UI at http://localhost:5266/
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "RPG Character Service API");
    c.RoutePrefix = ""; 
});

// Configure routing
app.UseRouting();
app.MapControllers();

app.Run();
