### Create a character
POST http://localhost:5266/api/v1/characters
Content-Type: application/json

{
  "name": "Pykey",
  "race": "Elf",
  "subRace": "High",
  "class": "Wizard"
}

###

### Get a character
GET http://localhost:5266/api/v1/characters/{{characterId}}
Accept: application/json

###

### Initialize character currency
POST http://localhost:5266/api/v1/characters/{{characterId}}/currency/init
Content-Type: application/json

{
  "amount": 100
}

###

### Delete a character
DELETE http://localhost:5266/api/v1/characters/{{characterId}}

###

### Update hit points
PATCH http://localhost:5266/api/v1/characters/{{characterId}}/stats/hitpoints
Content-Type: application/json

{
  "delta": 5
}

###

### Equip armor
@armorId = 40
PATCH http://localhost:5266/api/v1/characters/{{characterId}}/equipment/armo/{{armorId}}

###

### Equip weapon
@weaponId = 4
PATCH http://localhost:5266/api/v1/characters/{{characterId}}/equipment/weapon/{{weaponId}}
Content-Type: application/json

{
  "offHand": true
}

###

### Modify currency
PATCH http://localhost:5266/api/v1/characters/{{characterId}}/currency
Content-Type: application/json

{
  "gold": 10,
  "silver": -5
}

###

### Exchange currency
PATCH http://localhost:5266/api/v1/characters/{{characterId}}/currency/exchange
Content-Type: application/json

{
  "from": "gold",
  "to": "silver",
  "amount": 1
}

###

### Roll a single die
GET http://localhost:5266/api/v1/dice/roll?sides=20&count=1
Accept: application/json

###

### Roll multiple dice
GET http://localhost:5266/api/v1/dice/roll?sides=6&count=4
Accept: application/json
