apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-sim-service
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: game-sim-service
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: metadata-service
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
