using Microsoft.EntityFrameworkCore.Migrations;

namespace RPGCharacterService.Infrastructure.Data.Migrations {
  /// <summary>
  /// Initial migration for the RPG database.
  /// Note: In a real project, this would be generated by the EF Core migration tools.
  /// For this interview project, this is a simplified version to show the approach.
  /// </summary>
  public class InitialMigration : Migration {
    /// <summary>
    /// Upgrades the database schema.
    /// </summary>
    protected override void Up(MigrationBuilder migrationBuilder) {
      // This would contain the SQL code from our schema file
      // In a real project, this would be generated by the EF Core migration tools
      migrationBuilder.Sql(File.ReadAllText("Schema/01_CreateTables.sql"));
      migrationBuilder.Sql(File.ReadAllText("Schema/02_SeedData.sql"));
    }

    /// <summary>
    /// Downgrades the database schema.
    /// </summary>
    protected override void Down(MigrationBuilder migrationBuilder) {
      // Drop all tables in reverse order
      migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS CharacterEquipment;
                DROP TABLE IF EXISTS WeaponStats;
                DROP TABLE IF EXISTS ArmorStats;
                DROP TABLE IF EXISTS AbilityScores;
                DROP TABLE IF EXISTS Currencies;
                DROP TABLE IF EXISTS Items;
                DROP TABLE IF EXISTS Characters;
            ");
    }
  }
}
