apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- game-sim-service/deployment.yaml
- metadata-service/deployment.yaml
- metadata-service/service.yaml

configMapGenerator:
- name: environment-config
  literals:
  - DYNAMODB_TABLE=${DYNAMODB_TABLE}
  - AWS_REGION=${AWS_REGION}
  - METADATA_SERVICE_URL=${METADATA_SERVICE_URL}
  - GAME_SIM_PORT=7777

images:
- name: game-sim-service
  newName: ${GAME_SIM_IMAGE}
- name: metadata-service
  newName: ${METADATA_SERVICE_IMAGE}
