apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata-service
  template:
    metadata:
      labels:
        app: metadata-service
    spec:
      containers:
      - name: metadata-service
        image: ${METADATA_SERVICE_IMAGE}
        ports:
        - containerPort: 8080
        env:
        - name: DYNAMODB_DB_PREFIX
          value: ${DYNAMODB_DB_PREFIX}
        - name: GAME_SIM_PORT
          value: "7777"
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
