apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: metadata-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
