apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-sim-service
spec:
  template:
    spec:
      containers:
      - name: game-sim-service
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: metadata-service
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
