name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore rpg-character-service/rpg-character-service.sln

    - name: Build
      run: dotnet build rpg-character-service/rpg-character-service.sln --no-restore

    - name: Test with coverage
      run: |
        dotnet test rpg-character-service/rpg-character-service.sln --collect:"XPlat Code Coverage" --results-directory:"${{ github.workspace }}/TestResults" --logger:"trx;LogFileName=test-results.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="${{ github.workspace }}/TestResults/coverage.cobertura.xml" --filter:"FullyQualifiedName!~Integration"

    - name: Generate coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:"${{ github.workspace }}/TestResults/coverage.cobertura.xml" -targetdir:"${{ github.workspace }}/TestResults/CoverageReport" -reporttypes:Html

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ${{ github.workspace }}/TestResults/test-results.trx

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ${{ github.workspace }}/TestResults/CoverageReport
